version: '2'
services:
    app:
        build: app
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cacti_data
            - SPRING_RABBITMQ_HOST=rabbitmq
        ports:
            - "8080:8080"
        depends_on:
            - postgres
            - rabbitmq
    postgres:
        build: postgres
        environment:
            - POSTGRES_PASSWORD=cacti  
        ports:
            - "5432:5432"
        volumes:
            - /c/temp:/var/lib/postgresql/data            
    rabbitmq:
        image: rabbitmq:management
        ports:
            - "15672:15672"